#!/usr/bin/env bash
# installs and starts nginx with custom index page
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sudo /etc/init.d/nginx start
