#!/usr/bin/env bash
# installs and starts nginx with custom index page, redirect, and custom 404 page
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
string='\\tlocation /redirect_me {\n\t\trewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\t}\n'
sudo sed -i "38i$string" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
string='\\n\terror_page 404 /custom_404.html;\n\tlocation /custom_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}'
sudo sed -i "41i$string" /etc/nginx/sites-available/default
sudo /etc/init.d/nginx start
