#!/usr/bin/env bash
# prints information about Best file

if [ -e "Best" ]
then
	echo "Best file exists"

	if [ -s "Best" ]
	then
		echo "Best file is not empty"
	else
		echo "Best file is empty"
	fi

	if [ -f "Best" ]
	then
		echo "Best is a regular file"
	fi

else
	echo "Best file does not exist"
fi
